IMPORT_DATA_TYPES = {'datasetId':'int', 
                 'contigId':'str', 
                'Average fold':'float',
                'Length':'int', 
                'Reference GC':'float',
                'Covered percent':'float', 
                'Covered bases':'int', 
                'Plus reads':'int', 
                'Minus reads':'int',
                'Median fold':'float', 
                'Read GC':'float', 
                'Complete Lineage':'str',
                'IMG scaffold_oid':'str',
                'Kingdom':'str', 
                'Phylum':'str',
                'Class':'str', 
                'Order':'str', 
                'Family':'str', 
                'Genus':'str',
                'Species':'str'
                }
